### ISSUE TITLE
Add Docker config

### ISSUE THREAD

**Issue by ivanfoong** [nicnicknicky/pimp-my-raspbian#13]
1. To install docker and docker-compose
2. Ability to specify insecure-registries in the file `/etc/docker/daemon.json`

Sample steps to install docker and docker-compose
```
curl -sSL https://get.docker.com | sh
sudo usermod -aG docker pi
sudo pip install docker-compose
```

Sample `daemon.json`
```
{
  "insecure-registries": [ "192.168.1.2:5000" ]
}
```

**Comment by nicnicknicky** [comment]
@ivanfoong working on this

**Comment by nicnicknicky** [comment]
https://github.com/nicnicknicky/pimp-my-raspbian/pull/16
