### ISSUE TITLE
script is stucked

### ISSUE THREAD

**Issue by TayKangSheng** [nicnicknicky/pimp-my-raspbian#5]
Not so sure whether its really stucked, but at the least the logs for these 3 commands are not shown in terminal when running `./setup`. 

Not so sure whether its affected by the last part `1> /dev/null` got extra space. 

```
DEBIAN_FRONTEND=noninteractive apt-get --yes update 1>/dev/null
DEBIAN_FRONTEND=noninteractive apt-get --yes upgrade 1>/dev/null
DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes apt-transport-https 1> /dev/null
```
https://github.com/nicnicknicky/pimp-my-raspbian/blob/master/setup#L65

**Comment by nicnicknicky** [comment]
update and upgrade takes especially long for GUI based images
